version: '3'
services:
  alarmpi:
    container_name: alarmpi
    build: .
    #environment:
    #  - DEBUG=True
    volumes:
      - "./config:/config"
    restart: always
    command: "python alarmpi config/config.yaml"
